### PR TITLE
Move Monitor Mode for Child to its own Service

### PR DESCRIPTION
**Pull request by fwiesel**
Needs to be re-based after the merge

### CODE REVIEW

**Comment by fwiesel** [comment]
To follow up on your [comment](https://github.com/enguerrand/child-monitor/pull/9#issuecomment-1953148992):

I've removed the pending intent, which simplifies the issue. The Activity doesn't get closed nor re-recreated.

I was opening and closing the activity several times, but could not produce any unexpected exceptions.
I'll have to try it on another android version.

**Comment by enguerrand** [comment]
Looks good, I agree that there is no real use case for the pending intent stuff on the child device.

I will try to take a closer look later today. As a general side note: Could you please avoid force-pushing? I don't mind having lots of commits and it reduces my brain overload when following up on incremental changes during the review process.

**Comment by enguerrand** [comment]
I have made some minor changes. I am happy to merge this now if you can rebase and mark it ready!

**Comment by enguerrand** [comment]
Thanks a lot (again)! And sorry for making you move this to a second PR, now it's all looking good I'll release everything in one go.

**Pull request merged**
